spring:
  profiles:
    active: Local

  application:
    name: H2Memory

  liquibase:
    change-log: classpath:db/liquibase-master.xml

server:
  port: 9000
  servlet:
    context-path: /h2

logging :
  level:
    liquibase : INFO
